### ISSUE TITLE
Can't type Handlebars brackets

### ISSUE THREAD

**Issue by elemdos** [mateomorris/migrate-emmet#4]
When I try typing two opening brackets for Handlebars templating, Emmet interrupts the process and makes it pretty difficult to write out the full string.

**Comment by jwynveen** [comment]
@mateomorris Can you give details about how to reproduce this?

With this code, I don't get any problem when typing 2 opening brackets for handlebars:

```
const state = EditorState.create({
      doc: "<main></main>",
      extensions: [
        basicSetup,
        // language.of(css()),
        language.of(html()),
        emmetExt({
          config: {
            type: 'html',
            syntax: 'html'
          }
        }),
        keymap.of([
          defaultTabBinding
        ])
      ]
    })
```

However, when I used the below (wrong language) when I first forgot to change everything from CSS to HTML, I did get an error where it automatically completed the first bracket to be `{}` and typing another resulted in `{}{}` that did cause an error with emmet. That is part of a wrong config though so probably doesn't need to be fixed:

```
const state = EditorState.create({
      doc: "main>div*3>ul>li*5",
      extensions: [
        basicSetup,
        language.of(css()),
        // language.of(html()),
        emmetExt({
          config: {
            type: 'html',
            syntax: 'html'
          }
        }),
        keymap.of([
          defaultTabBinding
        ])
      ]
    })
```

**Comment by jwynveen** [comment]
I think this issue can be closed, unless a consistent reproduction can be shown

**Comment by elemdos** [comment]
This is weird, I'm still seeing this issue. @jwynveen what happens when you type two opening brackets? 
![image](https://user-images.githubusercontent.com/39444813/120655366-e9aaa780-c482-11eb-805d-d5e4dfae0991.png)

**Comment by jwynveen** [comment]
Oh, I forgot to test the double bracket issue. My bad
