### ISSUE TITLE
Broken CSS selectors

### ISSUE THREAD

**Issue by elemdos** [mateomorris/migrate-emmet#5]
When you type a selector and brackets, Emmet tries expanding it and deletes the brackets.
![image](https://user-images.githubusercontent.com/39444813/119530485-56d38400-bd83-11eb-8bda-9461225fb819.png)

**Comment by elemdos** [comment]
Actually, I can't seem to get the language to switch at all. Not sure what I'm doing wrong. I pushed my current setup so you can see what I'm talking about @jwynveen

**Comment by elemdos** [comment]
It's treating CSS like HTML even though the language and syntax are set to CSS

![image](https://user-images.githubusercontent.com/39444813/120116966-275db680-c18b-11eb-895a-2f7ea2915010.png)

**Comment by jwynveen** [comment]
This should be fixed and can be closed
