### ISSUE TITLE
Preview appearing for root-level styles

### ISSUE THREAD

**Issue by elemdos** [mateomorris/migrate-emmet#6]
The dialog box apepars for styles when outside of a selector, should only appear within it. image
![image](https://user-images.githubusercontent.com/39444813/119530579-6f439e80-bd83-11eb-8d71-8343c76d2337.png)

**Comment by jwynveen** [comment]
We should probably turn off the CSS peek in CSS files/editors, correct? @mateomorris

**Comment by elemdos** [comment]
Yeah, I removed it from the current setup
