### ISSUE TITLE
Auto-place cursor

### ISSUE THREAD

**Issue by elemdos** [mateomorris/migrate-emmet#7]
When expanding an abbreviation, the cursor jumps to the end of the expanded markup instead of jumping to the relevant spot within the string (e.g. between the tags), which is the expected Emmet behavior.

**Comment by jwynveen** [comment]
@mateomorris Do you have links to documentation or examples of the expected Emmet behavior in terms of knowing what is the expected cursor position?

**Comment by elemdos** [comment]
Still looking for documentation, but [Tailwind Play](https://play.tailwindcss.com/) is a good example of what the functionality should ultimately look like: When you press Tab the first time, it expands the markup and places your cursor at the first position. If there are others positions (like when building a list), then subsequent Tab presses move the cursor to the next place in the HTML. The idea is similar for CSS, but I imagine in that case there would just be one position to move the cursor to (between the `{}`).
